// AUTO-GENERATED by scripts/gen-crop-tiles.mjs — edit there and re-run, not here.
// The crop catalog: the single source of truth for the visual picker, marketplace
// category filters, and default listing images.

export interface CropCategory {
  key: string
  label: string
}

export interface CropOption {
  key: string
  label: string
  category: string
  image: string
}

export const CROP_CATEGORIES: CropCategory[] = [
  { key: 'vegetables', label: "Vegetables" },
  { key: 'fruits', label: "Fruits" },
  { key: 'grains', label: "Grains & Cereals" },
  { key: 'roots', label: "Roots & Tubers" },
  { key: 'legumes', label: "Legumes" },
  { key: 'cash', label: "Cash Crops" },
  { key: 'livestock', label: "Livestock & Poultry" },
  { key: 'herbs', label: "Herbs & Spices" },
]

export const CROPS: CropOption[] = [
  { key: 'tomatoes', label: "Tomatoes", category: 'vegetables', image: '/crops/tomatoes.svg' },
  { key: 'onions', label: "Onions", category: 'vegetables', image: '/crops/onions.svg' },
  { key: 'pepper', label: "Pepper", category: 'vegetables', image: '/crops/pepper.svg' },
  { key: 'garden-eggs', label: "Garden Eggs", category: 'vegetables', image: '/crops/garden-eggs.svg' },
  { key: 'okra', label: "Okra", category: 'vegetables', image: '/crops/okra.svg' },
  { key: 'cabbage', label: "Cabbage", category: 'vegetables', image: '/crops/cabbage.svg' },
  { key: 'carrot', label: "Carrot", category: 'vegetables', image: '/crops/carrot.svg' },
  { key: 'lettuce', label: "Lettuce", category: 'vegetables', image: '/crops/lettuce.svg' },
  { key: 'mango', label: "Mango", category: 'fruits', image: '/crops/mango.svg' },
  { key: 'pineapple', label: "Pineapple", category: 'fruits', image: '/crops/pineapple.svg' },
  { key: 'banana', label: "Banana", category: 'fruits', image: '/crops/banana.svg' },
  { key: 'plantain', label: "Plantain", category: 'fruits', image: '/crops/plantain.svg' },
  { key: 'orange', label: "Orange", category: 'fruits', image: '/crops/orange.svg' },
  { key: 'pawpaw', label: "Pawpaw", category: 'fruits', image: '/crops/pawpaw.svg' },
  { key: 'watermelon', label: "Watermelon", category: 'fruits', image: '/crops/watermelon.svg' },
  { key: 'avocado', label: "Avocado", category: 'fruits', image: '/crops/avocado.svg' },
  { key: 'maize', label: "Maize", category: 'grains', image: '/crops/maize.svg' },
  { key: 'rice', label: "Rice", category: 'grains', image: '/crops/rice.svg' },
  { key: 'millet', label: "Millet", category: 'grains', image: '/crops/millet.svg' },
  { key: 'sorghum', label: "Sorghum", category: 'grains', image: '/crops/sorghum.svg' },
  { key: 'cassava', label: "Cassava", category: 'roots', image: '/crops/cassava.svg' },
  { key: 'yam', label: "Yam", category: 'roots', image: '/crops/yam.svg' },
  { key: 'cocoyam', label: "Cocoyam", category: 'roots', image: '/crops/cocoyam.svg' },
  { key: 'sweet-potato', label: "Sweet Potato", category: 'roots', image: '/crops/sweet-potato.svg' },
  { key: 'potato', label: "Potato", category: 'roots', image: '/crops/potato.svg' },
  { key: 'cowpea', label: "Cowpea (Beans)", category: 'legumes', image: '/crops/cowpea.svg' },
  { key: 'groundnut', label: "Groundnut", category: 'legumes', image: '/crops/groundnut.svg' },
  { key: 'soybean', label: "Soybean", category: 'legumes', image: '/crops/soybean.svg' },
  { key: 'bambara-beans', label: "Bambara Beans", category: 'legumes', image: '/crops/bambara-beans.svg' },
  { key: 'cocoa', label: "Cocoa", category: 'cash', image: '/crops/cocoa.svg' },
  { key: 'coffee', label: "Coffee", category: 'cash', image: '/crops/coffee.svg' },
  { key: 'cashew', label: "Cashew", category: 'cash', image: '/crops/cashew.svg' },
  { key: 'oil-palm', label: "Oil Palm", category: 'cash', image: '/crops/oil-palm.svg' },
  { key: 'shea', label: "Shea", category: 'cash', image: '/crops/shea.svg' },
  { key: 'cotton', label: "Cotton", category: 'cash', image: '/crops/cotton.svg' },
  { key: 'rubber', label: "Rubber", category: 'cash', image: '/crops/rubber.svg' },
  { key: 'poultry', label: "Chicken / Poultry", category: 'livestock', image: '/crops/poultry.svg' },
  { key: 'eggs', label: "Eggs", category: 'livestock', image: '/crops/eggs.svg' },
  { key: 'goat', label: "Goat", category: 'livestock', image: '/crops/goat.svg' },
  { key: 'sheep', label: "Sheep", category: 'livestock', image: '/crops/sheep.svg' },
  { key: 'cattle', label: "Cattle", category: 'livestock', image: '/crops/cattle.svg' },
  { key: 'pig', label: "Pig", category: 'livestock', image: '/crops/pig.svg' },
  { key: 'fish', label: "Fish", category: 'livestock', image: '/crops/fish.svg' },
  { key: 'ginger', label: "Ginger", category: 'herbs', image: '/crops/ginger.svg' },
  { key: 'garlic', label: "Garlic", category: 'herbs', image: '/crops/garlic.svg' },
  { key: 'turmeric', label: "Turmeric", category: 'herbs', image: '/crops/turmeric.svg' },
  { key: 'black-pepper', label: "Black Pepper", category: 'herbs', image: '/crops/black-pepper.svg' },
  { key: 'lemongrass', label: "Lemongrass", category: 'herbs', image: '/crops/lemongrass.svg' },
  { key: 'basil', label: "Basil", category: 'herbs', image: '/crops/basil.svg' },
]

const BY_LABEL = new Map(CROPS.map((c) => [c.label.toLowerCase(), c]))
const BY_KEY = new Map(CROPS.map((c) => [c.key, c]))

/** Best-effort match of a free-text crop name to a catalogue entry. */
export function findCrop(crop: string | null | undefined): CropOption | undefined {
  if (!crop) return undefined
  const c = crop.trim().toLowerCase()
  if (!c) return undefined
  const exact = BY_LABEL.get(c) ?? BY_KEY.get(c)
  if (exact) return exact
  return CROPS.find((opt) => c.includes(opt.key) || opt.label.toLowerCase().includes(c) || c.includes(opt.label.toLowerCase().split(' ')[0]))
}

/** Resolves a crop name to its tile image, falling back to a neutral tile. */
export function cropImage(crop: string | null | undefined): string {
  return findCrop(crop)?.image ?? '/crops/_fallback.svg'
}

/** Resolves a crop name to its category label (e.g. for display). */
export function cropCategoryLabel(category: string | null | undefined): string {
  if (!category) return 'Other'
  return CROP_CATEGORIES.find((c) => c.key === category)?.label ?? 'Other'
}
